Repository mikf/gallery-dl, pull requests merged in 2024-11, with the labels that each got.

#6411 [bluesky] Match fxbsky.app and vxbsky.app urls
  gallery_dl/extractor/bluesky.py
  test/results/bluesky.py
Labels: site:url

#6437 [philomena] switch default ponybooru filter to get everything by default
  gallery_dl/extractor/philomena.py
Labels: site:enhancement

#6432 [koharu] updat root and root_api change
  gallery_dl/extractor/koharu.py
  test/results/koharu.py
Labels: site:support, nsfw

#5626 [facebook] add support
  docs/configuration.rst
  docs/supportedsites.md
  gallery_dl/extractor/__init__.py
  gallery_dl/extractor/facebook.py
  scripts/supportedsites.py
  test/results/facebook.py
Labels: site:support

#6501 [docs] update gallery-dl.conf
  docs/gallery-dl.conf
  scripts/docs_compare.py
Labels: documentation
