Repository mikf/gallery-dl, pull requests merged in 2025-04, with the labels that each got.

#7353 [discord] fix "parent" keyword inconsistency (#7341)
  gallery_dl/extractor/discord.py
Labels: site:bug, site:enhancement, site:metadata

#7241 [Instagram] Handle instagram.com/share/ URLs generated by the mobile app
  gallery_dl/extractor/instagram.py
  test/results/instagram.py
Labels: site:feature

#7409 [pictoa] Adding extractor
  docs/supportedsites.md
  gallery_dl/extractor/__init__.py
  gallery_dl/extractor/pictoa.py
  test/results/pictoa.py
Labels: site:support, nsfw

#7411 [itaku] Add a new extractor for Itaku stars
  docs/supportedsites.md
  gallery_dl/extractor/itaku.py
  test/results/itaku.py
Labels: site:feature

#7412 [weasyl] Set gallery-dl user agent to match danbooru user agent format, for weasyl
  docs/configuration.rst
  gallery_dl/extractor/weasyl.py
Labels: site:enhancement

#7414 [pixiv] fix user details request not being cached, causing extra requests
  gallery_dl/extractor/pixiv.py
Labels: site:enhancement

#7435 [pixiv] fix novel embeds with AJAX request
  gallery_dl/extractor/pixiv.py
Labels: site:enhancement
